interface District {
  name: string;
  code: string;
}

interface State {
  name: string;
  code: string;
  districts: District[];
}

export const indianStates: State[] = [
  {
    name: "Andhra Pradesh",
    code: "AP",
    districts: [
      { name: "Anantapur", code: "ANT" },
      { name: "Chittoor", code: "CHT" },
      { name: "East Godavari", code: "EGD" },
      { name: "Guntur", code: "GNT" },
      { name: "Krishna", code: "KRI" },
      { name: "Kurnool", code: "KUR" },
      { name: "Prakasam", code: "PRK" },
      { name: "Nellore", code: "NEL" },
      { name: "Srikakulam", code: "SRI" },
      { name: "Visakhapatnam", code: "VSK" },
      { name: "Vizianagaram", code: "VZM" },
      { name: "West Godavari", code: "WGD" },
      { name: "Parvathipuram Manyam", code: "PVM" },
      { name: "Alluri Sitharama Raju", code: "ASR" },
      { name: "Anakapalli", code: "ANK" },
      { name: "Kakinada", code: "KKD" },
      { name: "Nandyal", code: "NDL" },
      { name: "Sri Sathya Sai", code: "SSS" },
      { name: "Tirupati", code: "TRP" },
      { name: "Bapatla", code: "BPT" },
      { name: "Eluru", code: "ELR" },
      { name: "Palnadu", code: "PLN" },
      { name: "NTR", code: "NTR" },
      { name: "Annamayya", code: "ANM" },
      { name: "Konaseema", code: "KNS" }
    ]
  },
  {
    name: "Telangana",
    code: "TG",
    districts: [
      { name: "Adilabad", code: "ADL" },
      { name: "Bhadradri Kothagudem", code: "BDK" },
      { name: "Hyderabad", code: "HYD" },
      { name: "Jagtial", code: "JGT" },
      { name: "Jangaon", code: "JNG" },
      { name: "Jayashankar Bhupalpally", code: "JSB" },
      { name: "Jogulamba Gadwal", code: "JGB" },
      { name: "Kamareddy", code: "KMR" },
      { name: "Karimnagar", code: "KNR" },
      { name: "Khammam", code: "KHM" },
      { name: "Komaram Bheem Asifabad", code: "KBA" },
      { name: "Mahabubabad", code: "MBD" },
      { name: "Mahabubnagar", code: "MBN" },
      { name: "Mancherial", code: "MCL" },
      { name: "Medak", code: "MDK" },
      { name: "Medchal–Malkajgiri", code: "MDM" },
      { name: "Mulugu", code: "MLG" },
      { name: "Nagarkurnool", code: "NGK" },
      { name: "Nalgonda", code: "NLG" },
      { name: "Narayanpet", code: "NRP" },
      { name: "Nirmal", code: "NML" },
      { name: "Nizamabad", code: "NZB" },
      { name: "Peddapalli", code: "PDP" },
      { name: "Rajanna Sircilla", code: "RJS" },
      { name: "Rangareddy", code: "RRD" },
      { name: "Sangareddy", code: "SGR" },
      { name: "Siddipet", code: "SDP" },
      { name: "Suryapet", code: "SRP" },
      { name: "Vikarabad", code: "VKB" },
      { name: "Wanaparthy", code: "WNP" },
      { name: "Warangal", code: "WGL" },
      { name: "Hanamkonda", code: "HNK" },
      { name: "Yadadri Bhuvanagiri", code: "YDB" }
    ]
  },
  {
    name: "Karnataka",
    code: "KA",
    districts: [
      { name: "Bagalkot", code: "BGK" },
      { name: "Ballari", code: "BLR" },
      { name: "Belagavi", code: "BGV" },
      { name: "Bengaluru Rural", code: "BGR" },
      { name: "Bengaluru Urban", code: "BGU" },
      { name: "Bidar", code: "BDR" },
      { name: "Chamarajanagar", code: "CMR" },
      { name: "Chikkaballapur", code: "CBP" },
      { name: "Chikkamagaluru", code: "CKM" },
      { name: "Chitradurga", code: "CTD" },
      { name: "Dakshina Kannada", code: "DKN" },
      { name: "Davanagere", code: "DVG" },
      { name: "Dharwad", code: "DHW" },
      { name: "Gadag", code: "GDG" },
      { name: "Hassan", code: "HSN" },
      { name: "Haveri", code: "HVR" },
      { name: "Kalaburagi", code: "KLB" },
      { name: "Kodagu", code: "KDG" },
      { name: "Kolar", code: "KLR" },
      { name: "Koppal", code: "KPL" },
      { name: "Mandya", code: "MND" },
      { name: "Mysuru", code: "MYS" },
      { name: "Raichur", code: "RCR" },
      { name: "Ramanagara", code: "RMN" },
      { name: "Shivamogga", code: "SMG" },
      { name: "Tumakuru", code: "TMK" },
      { name: "Udupi", code: "UDP" },
      { name: "Uttara Kannada", code: "UTK" },
      { name: "Vijayapura", code: "VJP" },
      { name: "Vijayanagara", code: "VJN" },
      { name: "Yadgir", code: "YDG" }
    ]
  },
  {
    name: "Maharashtra",
    code: "MH",
    districts: [
      { name: "Ahmednagar", code: "AHM" },
      { name: "Akola", code: "AKL" },
      { name: "Amravati", code: "AMR" },
      { name: "Aurangabad", code: "AUR" },
      { name: "Beed", code: "BED" },
      { name: "Bhandara", code: "BHD" },
      { name: "Buldhana", code: "BLD" },
      { name: "Chandrapur", code: "CHD" },
      { name: "Dhule", code: "DHU" },
      { name: "Gadchiroli", code: "GDC" },
      { name: "Gondia", code: "GND" },
      { name: "Hingoli", code: "HNG" },
      { name: "Jalgaon", code: "JLG" },
      { name: "Jalna", code: "JLN" },
      { name: "Kolhapur", code: "KLP" },
      { name: "Latur", code: "LTR" },
      { name: "Mumbai City", code: "MBC" },
      { name: "Mumbai Suburban", code: "MBS" },
      { name: "Nagpur", code: "NGP" },
      { name: "Nanded", code: "NND" },
      { name: "Nandurbar", code: "NDB" },
      { name: "Nashik", code: "NSK" },
      { name: "Osmanabad", code: "OSM" },
      { name: "Palghar", code: "PLG" },
      { name: "Parbhani", code: "PRB" },
      { name: "Pune", code: "PUN" },
      { name: "Raigad", code: "RGD" },
      { name: "Ratnagiri", code: "RTN" },
      { name: "Sangli", code: "SNG" },
      { name: "Satara", code: "STR" },
      { name: "Sindhudurg", code: "SDG" },
      { name: "Solapur", code: "SLP" },
      { name: "Thane", code: "THN" },
      { name: "Wardha", code: "WRD" },
      { name: "Washim", code: "WSM" },
      { name: "Yavatmal", code: "YTM" }
    ]
  },
  {
    name: "Tamil Nadu",
    code: "TN",
    districts: [
      { name: "Ariyalur", code: "ARL" },
      { name: "Chengalpattu", code: "CGP" },
      { name: "Chennai", code: "CHN" },
      { name: "Coimbatore", code: "CBE" },
      { name: "Cuddalore", code: "CDL" },
      { name: "Dharmapuri", code: "DHP" },
      { name: "Dindigul", code: "DGL" },
      { name: "Erode", code: "ERD" },
      { name: "Kallakurichi", code: "KLK" },
      { name: "Kanchipuram", code: "KCP" },
      { name: "Kanniyakumari", code: "KNK" },
      { name: "Karur", code: "KRR" },
      { name: "Krishnagiri", code: "KGI" },
      { name: "Madurai", code: "MDU" },
      { name: "Mayiladuthurai", code: "MYL" },
      { name: "Nagapattinam", code: "NGP" },
      { name: "Namakkal", code: "NMK" },
      { name: "Nilgiris", code: "NLG" },
      { name: "Perambalur", code: "PMB" },
      { name: "Pudukkottai", code: "PDK" },
      { name: "Ramanathapuram", code: "RMP" },
      { name: "Ranipet", code: "RNP" },
      { name: "Salem", code: "SLM" },
      { name: "Sivaganga", code: "SVG" },
      { name: "Tenkasi", code: "TNK" },
      { name: "Thanjavur", code: "TNJ" },
      { name: "Theni", code: "THN" },
      { name: "Thoothukudi", code: "TUT" },
      { name: "Tiruchirappalli", code: "TRI" },
      { name: "Tirunelveli", code: "TNV" },
      { name: "Tirupathur", code: "TPT" },
      { name: "Tiruppur", code: "TPR" },
      { name: "Tiruvallur", code: "TRL" },
      { name: "Tiruvannamalai", code: "TVM" },
      { name: "Tiruvarur", code: "TVR" },
      { name: "Vellore", code: "VLR" },
      { name: "Viluppuram", code: "VPM" },
      { name: "Virudhunagar", code: "VNR" }
    ]
  },
  {
    name: "Kerala",
    code: "KL",
    districts: [
      { name: "Alappuzha", code: "ALP" },
      { name: "Ernakulam", code: "EKM" },
      { name: "Idukki", code: "IDK" },
      { name: "Kannur", code: "KNR" },
      { name: "Kasaragod", code: "KSD" },
      { name: "Kollam", code: "KLM" },
      { name: "Kottayam", code: "KTM" },
      { name: "Kozhikode", code: "KZD" },
      { name: "Malappuram", code: "MLP" },
      { name: "Palakkad", code: "PKD" },
      { name: "Pathanamthitta", code: "PTA" },
      { name: "Thiruvananthapuram", code: "TVM" },
      { name: "Thrissur", code: "TSR" },
      { name: "Wayanad", code: "WYD" }
    ]
  },
  {
    name: "Gujarat",
    code: "GJ",
    districts: [
      { name: "Ahmedabad", code: "AMD" },
      { name: "Amreli", code: "AML" },
      { name: "Anand", code: "AND" },
      { name: "Aravalli", code: "ARV" },
      { name: "Banaskantha", code: "BNK" },
      { name: "Bharuch", code: "BHR" },
      { name: "Bhavnagar", code: "BVN" },
      { name: "Botad", code: "BTD" },
      { name: "Chhota Udaipur", code: "CHU" },
      { name: "Dahod", code: "DHD" },
      { name: "Dang", code: "DNG" },
      { name: "Devbhoomi Dwarka", code: "DBD" },
      { name: "Gandhinagar", code: "GND" },
      { name: "Gir Somnath", code: "GRS" },
      { name: "Jamnagar", code: "JMN" },
      { name: "Junagadh", code: "JND" },
      { name: "Kheda", code: "KHD" },
      { name: "Kutch", code: "KTC" },
      { name: "Mahisagar", code: "MHG" },
      { name: "Mehsana", code: "MHS" },
      { name: "Morbi", code: "MRB" },
      { name: "Narmada", code: "NRM" },
      { name: "Navsari", code: "NVS" },
      { name: "Panchmahal", code: "PNC" },
      { name: "Patan", code: "PTN" },
      { name: "Porbandar", code: "PBR" },
      { name: "Rajkot", code: "RJK" },
      { name: "Sabarkantha", code: "SBK" },
      { name: "Surat", code: "SRT" },
      { name: "Surendranagar", code: "SRN" },
      { name: "Tapi", code: "TAP" },
      { name: "Vadodara", code: "VDD" },
      { name: "Valsad", code: "VLS" }
    ]
  },
  {
    name: "Uttar Pradesh",
    code: "UP",
    districts: [
      { name: "Agra", code: "AGR" },
      { name: "Aligarh", code: "ALG" },
      { name: "Prayagraj", code: "PRY" },
      { name: "Ambedkar Nagar", code: "AMN" },
      { name: "Amethi", code: "AMT" },
      { name: "Amroha", code: "AMR" },
      { name: "Auraiya", code: "AUR" },
      { name: "Ayodhya", code: "AYD" },
      { name: "Azamgarh", code: "AZM" },
      { name: "Badaun", code: "BDN" },
      { name: "Bahraich", code: "BHR" },
      { name: "Ballia", code: "BLA" },
      { name: "Balrampur", code: "BLP" },
      { name: "Banda", code: "BND" },
      { name: "Barabanki", code: "BRB" },
      { name: "Bareilly", code: "BRL" },
      { name: "Basti", code: "BST" },
      { name: "Bhadohi", code: "BHD" },
      { name: "Bijnor", code: "BJN" },
      { name: "Budaun", code: "BDN" },
      { name: "Bulandshahr", code: "BLS" },
      { name: "Chandauli", code: "CHD" },
      { name: "Chitrakoot", code: "CHT" },
      { name: "Deoria", code: "DEO" },
      { name: "Etah", code: "ETH" },
      { name: "Etawah", code: "ETW" },
      { name: "Farrukhabad", code: "FRK" },
      { name: "Fatehpur", code: "FTP" },
      { name: "Firozabad", code: "FZD" },
      { name: "Gautam Buddha Nagar", code: "GBN" },
      { name: "Ghaziabad", code: "GZB" },
      { name: "Ghazipur", code: "GZP" },
      { name: "Gonda", code: "GND" },
      { name: "Gorakhpur", code: "GKP" },
      { name: "Hamirpur", code: "HMR" },
      { name: "Hapur", code: "HPR" },
      { name: "Hardoi", code: "HRD" },
      { name: "Hathras", code: "HTR" },
      { name: "Jalaun", code: "JLN" },
      { name: "Jaunpur", code: "JNP" },
      { name: "Jhansi", code: "JHN" },
      { name: "Kannauj", code: "KNJ" },
      { name: "Kanpur Dehat", code: "KPD" },
      { name: "Kanpur Nagar", code: "KNP" },
      { name: "Kasganj", code: "KSG" },
      { name: "Kaushambi", code: "KSB" },
      { name: "Kushinagar", code: "KSN" },
      { name: "Lakhimpur Kheri", code: "LKH" },
      { name: "Lalitpur", code: "LLP" },
      { name: "Lucknow", code: "LKO" },
      { name: "Maharajganj", code: "MHG" },
      { name: "Mahoba", code: "MHB" },
      { name: "Mainpuri", code: "MNP" },
      { name: "Mathura", code: "MTR" },
      { name: "Mau", code: "MAU" },
      { name: "Meerut", code: "MRT" },
      { name: "Mirzapur", code: "MZP" },
      { name: "Moradabad", code: "MBD" },
      { name: "Muzaffarnagar", code: "MZN" },
      { name: "Pilibhit", code: "PLB" },
      { name: "Pratapgarh", code: "PRG" },
      { name: "Rae Bareli", code: "RBL" },
      { name: "Rampur", code: "RMP" },
      { name: "Saharanpur", code: "SHP" },
      { name: "Sambhal", code: "SMB" },
      { name: "Sant Kabir Nagar", code: "SKN" },
      { name: "Shahjahanpur", code: "SJP" },
      { name: "Shamli", code: "SML" },
      { name: "Shrawasti", code: "SRW" },
      { name: "Siddharthnagar", code: "SDN" },
      { name: "Sitapur", code: "STP" },
      { name: "Sonbhadra", code: "SNB" },
      { name: "Sultanpur", code: "SLP" },
      { name: "Unnao", code: "UNO" },
      { name: "Varanasi", code: "VNS" }
    ]
  },
  {
    name: "Bihar",
    code: "BR",
    districts: [
      { name: "Araria", code: "ARA" },
      { name: "Arwal", code: "ARW" },
      { name: "Aurangabad", code: "AUR" },
      { name: "Banka", code: "BNK" },
      { name: "Begusarai", code: "BGS" },
      { name: "Bhagalpur", code: "BGP" },
      { name: "Bhojpur", code: "BHJ" },
      { name: "Buxar", code: "BXR" },
      { name: "Darbhanga", code: "DRB" },
      { name: "East Champaran", code: "ECH" },
      { name: "Gaya", code: "GYA" },
      { name: "Gopalganj", code: "GPL" },
      { name: "Jamui", code: "JMU" },
      { name: "Jehanabad", code: "JHB" },
      { name: "Kaimur", code: "KMR" },
      { name: "Katihar", code: "KTR" },
      { name: "Khagaria", code: "KHG" },
      { name: "Kishanganj", code: "KSG" },
      { name: "Lakhisarai", code: "LKS" },
      { name: "Madhepura", code: "MDP" },
      { name: "Madhubani", code: "MDB" },
      { name: "Munger", code: "MNG" },
      { name: "Muzaffarpur", code: "MZP" },
      { name: "Nalanda", code: "NLD" },
      { name: "Nawada", code: "NWD" },
      { name: "Patna", code: "PAT" },
      { name: "Purnia", code: "PUR" },
      { name: "Rohtas", code: "RHT" },
      { name: "Saharsa", code: "SHS" },
      { name: "Samastipur", code: "SMS" },
      { name: "Saran", code: "SRN" },
      { name: "Sheikhpura", code: "SKP" },
      { name: "Sheohar", code: "SHR" },
      { name: "Sitamarhi", code: "STM" },
      { name: "Siwan", code: "SWN" },
      { name: "Supaul", code: "SPL" },
      { name: "Vaishali", code: "VSL" },
      { name: "West Champaran", code: "WCH" }
    ]
  },
  {
    name: "Madhya Pradesh",
    code: "MP",
    districts: [
      { name: "Agar Malwa", code: "AGM" },
      { name: "Alirajpur", code: "ALP" },
      { name: "Anuppur", code: "ANP" },
      { name: "Ashoknagar", code: "ASN" },
      { name: "Balaghat", code: "BLG" },
      { name: "Barwani", code: "BRW" },
      { name: "Betul", code: "BTL" },
      { name: "Bhind", code: "BHD" },
      { name: "Bhopal", code: "BPL" },
      { name: "Burhanpur", code: "BHP" },
      { name: "Chhatarpur", code: "CHP" },
      { name: "Chhindwara", code: "CHW" },
      { name: "Damoh", code: "DMH" },
      { name: "Datia", code: "DAT" },
      { name: "Dewas", code: "DWS" },
      { name: "Dhar", code: "DHR" },
      { name: "Dindori", code: "DND" },
      { name: "Guna", code: "GNA" },
      { name: "Gwalior", code: "GWL" },
      { name: "Harda", code: "HRD" },
      { name: "Hoshangabad", code: "HSB" },
      { name: "Indore", code: "IND" },
      { name: "Jabalpur", code: "JBP" },
      { name: "Jhabua", code: "JHB" },
      { name: "Katni", code: "KTN" },
      { name: "Khandwa", code: "KHW" },
      { name: "Khargone", code: "KHG" },
      { name: "Mandla", code: "MND" },
      { name: "Mandsaur", code: "MDS" },
      { name: "Morena", code: "MRN" },
      { name: "Narsinghpur", code: "NRP" },
      { name: "Neemuch", code: "NMH" },
      { name: "Niwari", code: "NWR" },
      { name: "Panna", code: "PNA" },
      { name: "Raisen", code: "RSN" },
      { name: "Rajgarh", code: "RJG" },
      { name: "Ratlam", code: "RTM" },
      { name: "Rewa", code: "RWA" },
      { name: "Sagar", code: "SGR" },
      { name: "Satna", code: "STN" },
      { name: "Sehore", code: "SHR" },
      { name: "Seoni", code: "SNI" },
      { name: "Shahdol", code: "SDL" },
      { name: "Shajapur", code: "SJP" },
      { name: "Sheopur", code: "SPR" },
      { name: "Shivpuri", code: "SVP" },
      { name: "Sidhi", code: "SDH" },
      { name: "Singrauli", code: "SGR" },
      { name: "Tikamgarh", code: "TKG" },
      { name: "Ujjain", code: "UJN" },
      { name: "Umaria", code: "UMR" },
      { name: "Vidisha", code: "VDS" },
      { name: "Chachaura", code: "CCR" },
      { name: "Maihar", code: "MHR" }
    ]
  },
  {
    name: "Rajasthan",
    code: "RJ",
    districts: [
      { name: "Ajmer", code: "AJM" },
      { name: "Alwar", code: "ALW" },
      { name: "Banswara", code: "BNS" },
      { name: "Baran", code: "BRN" },
      { name: "Barmer", code: "BMR" },
      { name: "Bharatpur", code: "BRT" },
      { name: "Bhilwara", code: "BHL" },
      { name: "Bikaner", code: "BKN" },
      { name: "Bundi", code: "BND" },
      { name: "Chittorgarh", code: "CHT" },
      { name: "Churu", code: "CHR" },
      { name: "Dausa", code: "DAS" },
      { name: "Dholpur", code: "DHP" },
      { name: "Dungarpur", code: "DGP" },
      { name: "Hanumangarh", code: "HMG" },
      { name: "Jaipur", code: "JPR" },
      { name: "Jaisalmer", code: "JSM" },
      { name: "Jalore", code: "JLR" },
      { name: "Jhalawar", code: "JHW" },
      { name: "Jhunjhunu", code: "JJN" },
      { name: "Jodhpur", code: "JDP" },
      { name: "Karauli", code: "KRL" },
      { name: "Kota", code: "KTA" },
      { name: "Nagaur", code: "NGR" },
      { name: "Pali", code: "PAL" },
      { name: "Pratapgarh", code: "PRP" },
      { name: "Rajsamand", code: "RJS" },
      { name: "Sawai Madhopur", code: "SWM" },
      { name: "Sikar", code: "SKR" },
      { name: "Sirohi", code: "SRH" },
      { name: "Sri Ganganagar", code: "GNG" },
      { name: "Tonk", code: "TNK" },
      { name: "Udaipur", code: "UDP" },
      { name: "Shahpura", code: "SHP" },
      { name: "Neem Ka Thana", code: "NKT" },
      { name: "Balotra", code: "BLT" },
      { name: "Beawar", code: "BWR" },
      { name: "Deeg", code: "DEG" },
      { name: "Didwana-Kuchaman", code: "DDK" },
      { name: "Dudu", code: "DUD" },
      { name: "Gangapur City", code: "GPC" },
      { name: "Jaipur North", code: "JPN" },
      { name: "Jaipur South", code: "JPS" },
      { name: "Jodhpur East", code: "JDE" },
      { name: "Jodhpur West", code: "JDW" },
      { name: "Kekri", code: "KKR" },
      { name: "Kotputli-Behror", code: "KPB" },
      { name: "Phalodi", code: "PHD" },
      { name: "Salumbar", code: "SLB" }
    ]
  },
  {
    name: "West Bengal",
    code: "WB",
    districts: [
      { name: "Alipurduar", code: "APD" },
      { name: "Bankura", code: "BNK" },
      { name: "Birbhum", code: "BRB" },
      { name: "Cooch Behar", code: "COB" },
      { name: "Dakshin Dinajpur", code: "DDP" },
      { name: "Darjeeling", code: "DJG" },
      { name: "Hooghly", code: "HOG" },
      { name: "Howrah", code: "HWH" },
      { name: "Jalpaiguri", code: "JAL" },
      { name: "Jhargram", code: "JHG" },
      { name: "Kalimpong", code: "KLM" },
      { name: "Kolkata", code: "KOL" },
      { name: "Malda", code: "MLD" },
      { name: "Murshidabad", code: "MSD" },
      { name: "Nadia", code: "NAD" },
      { name: "North 24 Parganas", code: "N24" },
      { name: "Paschim Bardhaman", code: "PWB" },
      { name: "Paschim Medinipur", code: "PMD" },
      { name: "Purba Bardhaman", code: "PBD" },
      { name: "Purba Medinipur", code: "PRM" },
      { name: "Purulia", code: "PRL" },
      { name: "South 24 Parganas", code: "S24" },
      { name: "Uttar Dinajpur", code: "UDP" }
    ]
  },
  {
    name: "Odisha",
    code: "OD",
    districts: [
      { name: "Angul", code: "ANG" },
      { name: "Balangir", code: "BLG" },
      { name: "Balasore", code: "BLS" },
      { name: "Bargarh", code: "BGR" },
      { name: "Bhadrak", code: "BHD" },
      { name: "Boudh", code: "BDH" },
      { name: "Cuttack", code: "CTC" },
      { name: "Deogarh", code: "DEO" },
      { name: "Dhenkanal", code: "DHN" },
      { name: "Gajapati", code: "GJP" },
      { name: "Ganjam", code: "GNJ" },
      { name: "Jagatsinghpur", code: "JGT" },
      { name: "Jajpur", code: "JJP" },
      { name: "Jharsuguda", code: "JHR" },
      { name: "Kalahandi", code: "KLH" },
      { name: "Kandhamal", code: "KND" },
      { name: "Kendrapara", code: "KDP" },
      { name: "Kendujhar", code: "KJR" },
      { name: "Khordha", code: "KHO" },
      { name: "Koraput", code: "KRP" },
      { name: "Malkangiri", code: "MLK" },
      { name: "Mayurbhanj", code: "MBJ" },
      { name: "Nabarangpur", code: "NBR" },
      { name: "Nayagarh", code: "NYG" },
      { name: "Nuapada", code: "NUA" },
      { name: "Puri", code: "PUR" },
      { name: "Rayagada", code: "RYG" },
      { name: "Sambalpur", code: "SBP" },
      { name: "Subarnapur", code: "SBN" },
      { name: "Sundargarh", code: "SNG" }
    ]
  },
  {
    name: "Assam",
    code: "AS",
    districts: [
      { name: "Baksa", code: "BKS" },
      { name: "Barpeta", code: "BPT" },
      { name: "Biswanath", code: "BSW" },
      { name: "Bongaigaon", code: "BGN" },
      { name: "Cachar", code: "CCR" },
      { name: "Charaideo", code: "CRD" },
      { name: "Chirang", code: "CHR" },
      { name: "Darrang", code: "DRG" },
      { name: "Dhemaji", code: "DHM" },
      { name: "Dhubri", code: "DHB" },
      { name: "Dibrugarh", code: "DBG" },
      { name: "Goalpara", code: "GLP" },
      { name: "Golaghat", code: "GLG" },
      { name: "Hailakandi", code: "HKD" },
      { name: "Hojai", code: "HJI" },
      { name: "Jorhat", code: "JRT" },
      { name: "Kamrup", code: "KMP" },
      { name: "Kamrup Metropolitan", code: "KMM" },
      { name: "Karbi Anglong", code: "KBA" },
      { name: "Karimganj", code: "KRG" },
      { name: "Kokrajhar", code: "KKJ" },
      { name: "Lakhimpur", code: "LKP" },
      { name: "Majuli", code: "MJL" },
      { name: "Morigaon", code: "MRG" },
      { name: "Nagaon", code: "NGN" },
      { name: "Nalbari", code: "NLB" },
      { name: "Sivasagar", code: "SVR" },
      { name: "Sonitpur", code: "SNT" },
      { name: "South Salmara Mankachar", code: "SSM" },
      { name: "Tinsukia", code: "TNK" },
      { name: "Udalguri", code: "UDL" },
      { name: "West Karbi Anglong", code: "WKA" },
      { name: "Bajali", code: "BJL" },
      { name: "Tamulpur", code: "TMP" }
    ]
  },
  {
    name: "Chhattisgarh",
    code: "CG",
    districts: [
      { name: "Balod", code: "BLD" },
      { name: "Baloda Bazar", code: "BDB" },
      { name: "Balrampur", code: "BRP" },
      { name: "Bastar", code: "BST" },
      { name: "Bemetara", code: "BMT" },
      { name: "Bijapur", code: "BJP" },
      { name: "Bilaspur", code: "BLS" },
      { name: "Dantewada", code: "DNT" },
      { name: "Dhamtari", code: "DHM" },
      { name: "Durg", code: "DRG" },
      { name: "Gariaband", code: "GRB" },
      { name: "Gaurela-Pendra-Marwahi", code: "GPM" },
      { name: "Janjgir-Champa", code: "JCH" },
      { name: "Jashpur", code: "JSP" },
      { name: "Kabirdham", code: "KBD" },
      { name: "Kanker", code: "KNK" },
      { name: "Kondagaon", code: "KGN" },
      { name: "Korba", code: "KRB" },
      { name: "Korea", code: "KOR" },
      { name: "Mahasamund", code: "MHS" },
      { name: "Mungeli", code: "MNG" },
      { name: "Narayanpur", code: "NRP" },
      { name: "Raigarh", code: "RGH" },
      { name: "Raipur", code: "RPR" },
      { name: "Rajnandgaon", code: "RJN" },
      { name: "Sukma", code: "SKM" },
      { name: "Surajpur", code: "SJP" },
      { name: "Surguja", code: "SRG" },
      { name: "Manendragarh-Chirmiri-Bharatpur", code: "MCB" },
      { name: "Mohla-Manpur-Ambagarh Chowki", code: "MMA" },
      { name: "Khairagarh-Chhuikhadan-Gandai", code: "KCG" },
      { name: "Sarangarh-Bilaigarh", code: "SBG" },
      { name: "Sakti", code: "SKT" }
    ]
  },
  {
    name: "Uttarakhand",
    code: "UK",
    districts: [
      { name: "Almora", code: "ALM" },
      { name: "Bageshwar", code: "BGS" },
      { name: "Chamoli", code: "CML" },
      { name: "Champawat", code: "CMP" },
      { name: "Dehradun", code: "DDN" },
      { name: "Haridwar", code: "HDW" },
      { name: "Nainital", code: "NTL" },
      { name: "Pauri Garhwal", code: "PGW" },
      { name: "Pithoragarh", code: "PTH" },
      { name: "Rudraprayag", code: "RPG" },
      { name: "Tehri Garhwal", code: "TGW" },
      { name: "Udham Singh Nagar", code: "USN" },
      { name: "Uttarkashi", code: "UTK" }
    ]
  },
  {
    name: "Himachal Pradesh",
    code: "HP",
    districts: [
      { name: "Bilaspur", code: "BLP" },
      { name: "Chamba", code: "CHB" },
      { name: "Hamirpur", code: "HMP" },
      { name: "Kangra", code: "KNG" },
      { name: "Kinnaur", code: "KNR" },
      { name: "Kullu", code: "KUL" },
      { name: "Lahaul and Spiti", code: "LAS" },
      { name: "Mandi", code: "MND" },
      { name: "Shimla", code: "SML" },
      { name: "Sirmaur", code: "SMR" },
      { name: "Solan", code: "SLN" },
      { name: "Una", code: "UNA" }
    ]
  },
  {
    name: "Jharkhand",
    code: "JH",
    districts: [
      { name: "Bokaro", code: "BKR" },
      { name: "Chatra", code: "CTR" },
      { name: "Deoghar", code: "DGR" },
      { name: "Dhanbad", code: "DHN" },
      { name: "Dumka", code: "DMK" },
      { name: "East Singhbhum", code: "ESB" },
      { name: "Garhwa", code: "GRH" },
      { name: "Giridih", code: "GRD" },
      { name: "Godda", code: "GDD" },
      { name: "Gumla", code: "GML" },
      { name: "Hazaribagh", code: "HZB" },
      { name: "Jamtara", code: "JMT" },
      { name: "Khunti", code: "KHT" },
      { name: "Koderma", code: "KDM" },
      { name: "Latehar", code: "LTR" },
      { name: "Lohardaga", code: "LHD" },
      { name: "Pakur", code: "PKR" },
      { name: "Palamu", code: "PLM" },
      { name: "Ramgarh", code: "RMG" },
      { name: "Ranchi", code: "RNC" },
      { name: "Sahibganj", code: "SBG" },
      { name: "Seraikela Kharsawan", code: "SRK" },
      { name: "Simdega", code: "SMD" },
      { name: "West Singhbhum", code: "WSB" }
    ]
  },
  {
    name: "Jammu and Kashmir",
    code: "JK",
    districts: [
      { name: "Anantnag", code: "ANG" },
      { name: "Bandipora", code: "BPR" },
      { name: "Baramulla", code: "BML" },
      { name: "Budgam", code: "BDG" },
      { name: "Doda", code: "DOD" },
      { name: "Ganderbal", code: "GBL" },
      { name: "Jammu", code: "JAM" },
      { name: "Kathua", code: "KTH" },
      { name: "Kishtwar", code: "KWR" },
      { name: "Kulgam", code: "KLG" },
      { name: "Kupwara", code: "KPW" },
      { name: "Poonch", code: "PNC" },
      { name: "Pulwama", code: "PLW" },
      { name: "Rajouri", code: "RAJ" },
      { name: "Ramban", code: "RBN" },
      { name: "Reasi", code: "RSI" },
      { name: "Samba", code: "SMB" },
      { name: "Shopian", code: "SPN" },
      { name: "Srinagar", code: "SGR" },
      { name: "Udhampur", code: "UDH" }
    ]
  },
  {
    name: "Goa",
    code: "GA",
    districts: [
      { name: "North Goa", code: "NGO" },
      { name: "South Goa", code: "SGO" }
    ]
  },
  {
    name: "Manipur",
    code: "MN",
    districts: [
      { name: "Bishnupur", code: "BSP" },
      { name: "Chandel", code: "CDL" },
      { name: "Churachandpur", code: "CCP" },
      { name: "Imphal East", code: "IME" },
      { name: "Imphal West", code: "IMW" },
      { name: "Jiribam", code: "JRB" },
      { name: "Kakching", code: "KCH" },
      { name: "Kamjong", code: "KMJ" },
      { name: "Kangpokpi", code: "KPI" },
      { name: "Noney", code: "NON" },
      { name: "Pherzawl", code: "PHZ" },
      { name: "Senapati", code: "SNP" },
      { name: "Tamenglong", code: "TML" },
      { name: "Tengnoupal", code: "TNG" },
      { name: "Thoubal", code: "THB" },
      { name: "Ukhrul", code: "UKH" }
    ]
  },
  {
    name: "Meghalaya",
    code: "ML",
    districts: [
      { name: "East Garo Hills", code: "EGH" },
      { name: "East Jaintia Hills", code: "EJH" },
      { name: "East Khasi Hills", code: "EKH" },
      { name: "North Garo Hills", code: "NGH" },
      { name: "Ri-Bhoi", code: "RBH" },
      { name: "South Garo Hills", code: "SGH" },
      { name: "South West Garo Hills", code: "SWG" },
      { name: "South West Khasi Hills", code: "SWK" },
      { name: "West Garo Hills", code: "WGH" },
      { name: "West Jaintia Hills", code: "WJH" },
      { name: "West Khasi Hills", code: "WKH" },
      { name: "Eastern West Khasi Hills", code: "EWK" }
    ]
  },
  {
    name: "Mizoram",
    code: "MZ",
    districts: [
      { name: "Aizawl", code: "AJL" },
      { name: "Champhai", code: "CMP" },
      { name: "Hnahthial", code: "HNA" },
      { name: "Khawzawl", code: "KZL" },
      { name: "Kolasib", code: "KLS" },
      { name: "Lawngtlai", code: "LWL" },
      { name: "Lunglei", code: "LGL" },
      { name: "Mamit", code: "MMT" },
      { name: "Saiha", code: "SAI" },
      { name: "Saitual", code: "STL" },
      { name: "Serchhip", code: "SCP" }
    ]
  },
  {
    name: "Nagaland",
    code: "NL",
    districts: [
      { name: "Chümoukedima", code: "CHM" },
      { name: "Dimapur", code: "DMP" },
      { name: "Kiphire", code: "KPH" },
      { name: "Kohima", code: "KMA" },
      { name: "Longleng", code: "LNG" },
      { name: "Mokokchung", code: "MKG" },
      { name: "Mon", code: "MON" },
      { name: "Noklak", code: "NKL" },
      { name: "Peren", code: "PRN" },
      { name: "Phek", code: "PHK" },
      { name: "Shamator", code: "SMT" },
      { name: "Tseminyü", code: "TSM" },
      { name: "Tuensang", code: "TNS" },
      { name: "Wokha", code: "WKA" },
      { name: "Zunheboto", code: "ZBT" },
      { name: "Niuland", code: "NLD" }
    ]
  },
  {
    name: "Sikkim",
    code: "SK",
    districts: [
      { name: "Gangtok", code: "GTK" },
      { name: "Gyalshing", code: "GYL" },
      { name: "Mangan", code: "MGN" },
      { name: "Namchi", code: "NMC" },
      { name: "Pakyong", code: "PKY" },
      { name: "Soreng", code: "SRG" }
    ]
  },
  {
    name: "Tripura",
    code: "TR",
    districts: [
      { name: "Dhalai", code: "DHL" },
      { name: "Gomati", code: "GMT" },
      { name: "Khowai", code: "KHW" },
      { name: "North Tripura", code: "NTR" },
      { name: "Sepahijala", code: "SPJ" },
      { name: "South Tripura", code: "STR" },
      { name: "Unakoti", code: "UNK" },
      { name: "West Tripura", code: "WTR" }
    ]
  },
  {
    name: "Arunachal Pradesh",
    code: "AR",
    districts: [
      { name: "Tawang", code: "TWG" },
      { name: "West Kameng", code: "WKM" },
      { name: "East Kameng", code: "EKM" },
      { name: "Papum Pare", code: "PPR" },
      { name: "Kurung Kumey", code: "KKM" },
      { name: "Kra Daadi", code: "KRD" },
      { name: "Lower Subansiri", code: "LSR" },
      { name: "Upper Subansiri", code: "USR" },
      { name: "West Siang", code: "WSG" },
      { name: "East Siang", code: "ESG" },
      { name: "Siang", code: "SNG" },
      { name: "Upper Siang", code: "USG" },
      { name: "Lower Siang", code: "LSG" },
      { name: "Lower Dibang Valley", code: "LDV" },
      { name: "Dibang Valley", code: "DBV" },
      { name: "Anjaw", code: "ANJ" },
      { name: "Lohit", code: "LHT" },
      { name: "Namsai", code: "NMS" },
      { name: "Changlang", code: "CHG" },
      { name: "Tirap", code: "TRP" },
      { name: "Longding", code: "LNG" },
      { name: "Kamle", code: "KML" },
      { name: "Lepa Rada", code: "LPR" },
      { name: "Pakke Kessang", code: "PKS" },
      { name: "Shi-Yomi", code: "SYM" }
    ]
  },
  {
    name: "Delhi",
    code: "DL",
    districts: [
      { name: "Central Delhi", code: "CDL" },
      { name: "East Delhi", code: "EDL" },
      { name: "New Delhi", code: "NDL" },
      { name: "North Delhi", code: "NDH" },
      { name: "North East Delhi", code: "NED" },
      { name: "North West Delhi", code: "NWD" },
      { name: "Shahdara", code: "SHD" },
      { name: "South Delhi", code: "SDL" },
      { name: "South East Delhi", code: "SED" },
      { name: "South West Delhi", code: "SWD" },
      { name: "West Delhi", code: "WDL" }
    ]
  },
  {
    name: "Puducherry",
    code: "PY",
    districts: [
      { name: "Karaikal", code: "KKL" },
      { name: "Mahe", code: "MAH" },
      { name: "Puducherry", code: "PDY" },
      { name: "Yanam", code: "YNM" }
    ]
  },
  {
    name: "Ladakh",
    code: "LA",
    districts: [
      { name: "Kargil", code: "KGL" },
      { name: "Leh", code: "LEH" }
    ]
  },
  {
    name: "Andaman and Nicobar Islands",
    code: "AN",
    districts: [
      { name: "Nicobar", code: "NCB" },
      { name: "North and Middle Andaman", code: "NMA" },
      { name: "South Andaman", code: "SAN" }
    ]
  },
  {
    name: "Chandigarh",
    code: "CH",
    districts: [
      { name: "Chandigarh", code: "CHD" }
    ]
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    code: "DH",
    districts: [
      { name: "Dadra and Nagar Haveli", code: "DNH" },
      { name: "Daman", code: "DMN" },
      { name: "Diu", code: "DIU" }
    ]
  },
  {
    name: "Lakshadweep",
    code: "LD",
    districts: [
      { name: "Lakshadweep", code: "LKD" }
    ]
  }
];

export const phoneRegex = {
  indian: /^(\+91|0)?[6789]\d{9}$/,
  international: /^\+[1-9]\d{1,14}$/
}; 